name: CI

on:
  schedule:
    - cron: '20 13 * * 4'
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    container:
      image: practicalscheme/gauche
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup package
        run: |
          apt-get update -y --allow-releaseinfo-change;
          apt-get install -y libsqlite3-dev;
      - name: CI
        run: ./run-ci.sh
